### ISSUE TITLE
Add prerending parameter support

### ISSUE THREAD

**Issue by ayalpani** [microlinkhq/microlinkjs#50]
Hi! Great service you are providing. I am currently evaluating it and it works great. 

But I just found that it does not seem to work with google URLs. Example:

https://www.google.de/search?q=hello+world

Gives me:

body: '{"status":"fail","message":"Scraping from \\"https://www.google.de/search?q=hello world\\" failed. Make sure your URL has HTML."}' }

Can you tell me why?
Best

P.S.: you can try this URL out in the search box on https://microlink.io/

**Comment by Kikobeats** [comment]
Hello!

This is behavior more related with the impossibility to scrape certain websites.

The component is doing an API call like this:
https://api.microlink.io/?url=https://www.google.de/search?q=hello+world

It "looks that doesn't work" because many sites (like Google, LinkedIn, etc) disable GET petitions that they detected that they are not real users.

However, you can make something tricky: Enable [prerender](https://docs.microlink.io/#prerender) feature. It performs a smart call like a browser. 

The API call looks like:
https://api.microlink.io/?url=https://www.google.de/search?q=hello+world&prerender

and magic! your expected data is here 😄

Currently microlink free API endpoint doesn't use `prerender` by default because it bloats the server. You can enable it, but because it consume more CPU and the response time is higher, it is not enabled by default (contact me for use a pro plan!)

On the other hand, we can add a `prerender` option into microlink.js to enable make API call with prerending enabled.

**Comment by ayalpani** [comment]
Hi @Kikobeats 

Thanks a lot, this helps! Looking forward to the option you will add :)

**Comment by Kikobeats** [comment]
Will be shipped at `1.2.0`.

**Comment by ayalpani** [comment]
Works like a charm, thank you!
